/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.newbie.websockethub;

import com.newbie.indexprice.core.IndexPricingEngine;
import com.newbie.indexprice.simpleimpl.IndexPricingEngineImpl;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        IndexPricingEngine indexPricingEngine=new IndexPricingEngineImpl();
        indexPricingEngine.init();
        indexPricingEngine.start();
    }
}

