/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.newbie.websockethub;

import io.netty.bootstrap.Bootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.channel.*;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.nio.NioSocketChannel;
import io.netty.handler.codec.http.HttpClientCodec;
import io.netty.handler.codec.http.HttpObjectAggregator;
import io.netty.handler.codec.http.websocketx.*;
import io.netty.handler.ssl.SslContext;
import io.netty.handler.ssl.SslContextBuilder;
import io.netty.handler.ssl.util.InsecureTrustManagerFactory;

import javax.net.ssl.SSLException;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.zip.GZIPInputStream;

public class KrakenWebSocketClient {

    private static final EventLoopGroup group = new NioEventLoopGroup();

    public static void main(String[] args) throws Exception {
        URI uri1 = new URI("wss://ws.kraken.com:443/");
        new KrakenWebSocketClient().connectToWebSocket(uri1, group);
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            group.shutdownGracefully();
        }));
    }

    private  void connectToWebSocket(URI uri, EventLoopGroup sharedGroup) throws InterruptedException {
        Bootstrap bootstrap = new Bootstrap();
        bootstrap.group(sharedGroup)
                .channel(NioSocketChannel.class)
                .handler(new ChannelInitializer<Channel>() {
                    @Override
                    protected void initChannel(Channel ch) throws Exception {
                        ChannelPipeline pipeline = ch.pipeline();
                        applySSLContextIfNeeded(uri,pipeline,ch);

                        pipeline.addLast(new HttpClientCodec(),
                                new HttpObjectAggregator(8192),
                                new WebSocketClientProtocolHandler(uri, WebSocketVersion.V13, null, false, null, 65536),
                                //WebSocketClientCompressionHandler.INSTANCE,
                        new SimpleChannelInboundHandler<WebSocketFrame>() {
                                    @Override
                                    protected void channelRead0(ChannelHandlerContext ctx, WebSocketFrame frame) throws Exception {
                                        if(frame instanceof TextWebSocketFrame){
                                            System.out.println("Received message from " + uri + ": " + ((TextWebSocketFrame)frame).text());
                                            return;
                                        }
                                        System.out.println("Received binary message from " + uri + ": "+frame.getClass());
                                        if(frame instanceof BinaryWebSocketFrame){
                                            BinaryWebSocketFrame binaryFrame = (BinaryWebSocketFrame) frame;
                                            ByteBuf content = binaryFrame.content();
                                            byte[] data = new byte[content.readableBytes()];
                                            content.readBytes(data);//ctx
                                            String value=new String(decompressGzip(data));
                                            System.out.println("value "+value);
//                                            if(value.startsWith("{\"ping")){
//                                                ctx.writeAndFlush(new TextWebSocketFrame(value.replace('i','o')));
//                                            }
//
//                                            System.out.println("value "+value);
                                        }

                                    }
                                });
                    }
                });

        Channel channel = bootstrap.connect(uri.getHost(), uri.getPort()).sync().channel();
        channel.writeAndFlush(new TextWebSocketFrame("{\"event\":\"subscribe\",\"pair\":[\"XBT/USD\"],\"subscription\":{\"name\":\"trade\"}}"));
        //channel.writeAndFlush(new TextWebSocketFrame("{\"sub\":\"market.ethusdt.trade.detail\",\"id\":\"crypto-ws-client\"}"));
        System.out.println("start working on coinbase");
        // 不要在这里关闭Future，因为我们想要保持连接开放
        //channel.closeFuture().await();
    }

    public static byte[] decompressGzip(byte[] compressedData) throws IOException {
        try (ByteArrayInputStream bin = new ByteArrayInputStream(compressedData);
             GZIPInputStream gzipInputStream = new GZIPInputStream(bin);
             ByteArrayOutputStream bout = new ByteArrayOutputStream()) {

            byte[] buffer = new byte[1024];
            int len;
            while ((len = gzipInputStream.read(buffer)) > 0) {
                bout.write(buffer, 0, len);
            }

            return bout.toByteArray();
        }
    }
    private void applySSLContextIfNeeded(URI uri, ChannelPipeline pipeline, Channel ch) throws SSLException, URISyntaxException {

        if(uri.getScheme().startsWith("wss")){
            SslContext sslCtx= SslContextBuilder.forClient()
                    .trustManager(InsecureTrustManagerFactory.INSTANCE).build();

            pipeline.addLast(sslCtx.newHandler(ch.alloc(), uri.getHost(), uri.getPort()));

        }

    }
}